### ISSUE TITLE
SV padding irregularities during eval of clinical NGS16S data

### ISSUE THREAD

**Issue by dhoogest** [nhoffman/dada2-nf#22]
https://github.com/nhoffman/dada2-nf/blob/79d9f75d852442012f72452845c939f3a4c5e332/bin/write_seqs.py#L126

Seems like there may be some logic to address when number of characters used for padding is determined. I haven't looked into the code in any depth, but am seeing sv labels that look like this, despite what look to be only 270 unique SVs and 351 'findings' across the samples in the batch:

```
(NGS16S_dev-env) dhoogest@naga:/molmicro/working/dhoogest/NGS16S_dev$ wc -l input/weights.csv
351 input/weights.csv
(NGS16S_dev-env) dhoogest@naga:/molmicro/working/dhoogest/NGS16S_dev$ head input/weights.csv
sv-000001:1029-38,sv-000001:1029-38,229876
sv-000001:1029-38,sv-000001:1029-37,58639
sv-000001:1029-38,sv-000001:1029-39,25168
sv-000001:1029-38,sv-000001:1029-35,13322
sv-000001:1029-38,sv-000001:1029-36,2679
sv-000002:1029-36,sv-000002:1029-36,100462
sv-000002:1029-36,sv-000002:1029-38,2
sv-000003:1029-36,sv-000003:1029-36,62393
sv-000004:1029-36,sv-000004:1029-36,57607
sv-000005:1029-36,sv-000005:1029-36,54300
(NGS16S_dev-env) dhoogest@naga:/molmicro/working/dhoogest/NGS16S_dev$ tail input/weights.csv
sv-000261:1029-39,sv-000261:1029-39,3
sv-000262:1029-35,sv-000262:1029-35,3
sv-000263:1029-39,sv-000263:1029-39,3
sv-000264:1029-36,sv-000264:1029-36,3
sv-000265:1029-35,sv-000265:1029-35,2
sv-000266:1029-36,sv-000266:1029-36,2
sv-000267:1029-39,sv-000267:1029-39,2
sv-000268:1029-36,sv-000268:1029-36,2
sv-000269:1029-37,sv-000269:1029-37,2
sv-000270:1029-37,sv-000270:1029-37,2
```

Expected padding logic would have had a max of two zeros preceding the numeric SV assignment, with `sv-001`  to `sv-270`  in this case.

**Comment by crosenth** [comment]
https://github.com/nhoffman/dada2-nf/blob/master/bin/write_seqs.py#L139

This looks like a bug.  You are expecting ceil(log10(351)+1) to be 4 right?

**Comment by nhoffman** [comment]
Yes - it should be 4. 

> padchars = math.ceil(math.log10(len(svlist) + 1))

I wonder if items in svlist are not unique?

**Comment by nhoffman** [comment]
Hmm, no, they appear to be unique. I'm not sure what's going on here based on the minimal test set - I think you will need to do some experiments with a run exhibiting this actual error.

**Comment by dhoogest** [comment]
This was from 2021 - I'd bet we addressed somewhere but didn't close

**Comment by dhoogest** [comment]
> This was from 2021 - I'd bet we addressed somewhere but didn't close

I'll just close now and we can reopen if padding is observed. I haven't seen any problems in recent memory, and don't think additional followup is worthwhile at this point given the age of the issue.
