### ISSUE TITLE
Why are there 2 requirements.txt files?

### ISSUE THREAD

**Issue by crosenth** [nhoffman/dada2-nf#30]

**Comment by crosenth** [comment]
[Here](https://github.com/nhoffman/dada2-nf/blob/master/requirements.txt) and [here](https://github.com/nhoffman/dada2-nf/blob/master/docker/requirements.txt)

**Comment by crosenth** [comment]
@mwohl @dhoogest

**Comment by dhoogest** [comment]
We fixed this oversight recently (the requirements.txt in `/docker` was the correct set of python deps)
