### ISSUE TITLE
singularity support

### ISSUE THREAD

**Issue by nhoffman** [nhoffman/dada2-nf#35]
Provide options for using Singularity containers, particularly locally.

**Comment by nhoffman** [comment]
@dhoogest - I pushed some changes that include a singularity profile. Want to give it a try?

**Comment by dhoogest** [comment]
Thanks! Profile additions make sense and @mwohl and I were gonna take few test runs for a spin by stalled when building a local singularity image. Looks like the current Singularity file in master references a `../setup.R` script which I think is expected to be in this repo? We hit this durung the `singularity build`:

```
INFO:    Copying ../setup.R to /tmp/rootfs-73be508f-4899-11ec-b17e-2c768a4f1764/tmp/
FATAL:   container creation failed: unable to copy files to container fs: while copying [../setup.R] to /tmp/rootfs-73be508f-4899-11ec-b17e-2c768a4f1764/tmp/: exit status 1: /bin/cp: cannot stat '../setup.R': No such file or directory
```

**Comment by mwohl** [comment]
@nhoffman I'm trying to test the singularity profile with this command:
```
./nextflow run main.nf -params-fil$ params-minimal.json -profile singularity
```
and the pipeline is hanging with no progress.  When I leave off the `-profile singularity`, it completes in under 2 minutes.  Is this the right command?  I see this:
```
Pulling Singularity image library://nhoffman/dada2-nf/dada2-nf:v1.14-3-gcfce178 [cache /mnt/disk15/
molmicro/working/molly/dev/dada2-nf/work/singularity/nhoffman-dada2-nf-dada2-nf-v1.14-3-gcfce178.im
g]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path:
/mnt/disk15/molmicro/working/molly/dev/dada2-nf/work/singularity -- Use env variable NXF_SINGULARIT
Y_CACHEDIR to specify a different location
```

**Comment by mwohl** [comment]
Well it seems like it worked for me on a subsequent try.  Not sure what happened before.
