### ISSUE TITLE
Restore output of error_model plots

### ISSUE THREAD

**Issue by dhoogest** [nhoffman/dada2-nf#71]
Looks like we need to add back `file("error_model_${batch}.png") into error_model_plots` in the learn_errors process in order to retain the .png plots in the published output. Current state only .rds files are ending up in output/error_models

**Comment by crosenth** [comment]
Looks like I removed it [here](https://github.com/nhoffman/dada2-nf/commit/61c0772b60239100c342f2d4bca8f8506d51e4a6#diff-6401496ba455b9488ffa902a6e4d7732b2c60ff2d77c5c3ef96b28a7ac7d3b28L338) and I have no idea why

**Comment by dhoogest** [comment]
PR for restore is ready for approval/merge/release. Sorry I missed the boat for the `1.20.0`  tag with this one - didn't notice it till later.
